name: "Deploy Flutter web app to github pages"
description: "Automates the build and deployment of your Flutter web app on Github gh pages"
author: "bluefireteam"

branding:
  color: blue
  icon: code

inputs:
  webRenderer:
    description: "Which web renderer to be used, default is auto"
    required: false
    default: auto
  workingDir:
    description: "The directory where the project is (default .)"
    required: false
    default: .
  targetBranch:
    description: "The branch where the build will be pushed, default is gh-pages"
    required: false
    default: gh-pages
  baseHref:
    description: "base href (if applicable)"
    required: false
    default: "/"
  customArgs:
    description: 'Custom args like: --dart-define="simple=example"'
    required: false
    default: ""
  compileToWasm:
    description: "Compile to wasm, if used this will ignore the webRenderer flag, default is false"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - run: flutter config --enable-web
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: |
        if [[ "${{inputs.compileToWasm}}" == "true" ]]; then
          flutter build web --release --wasm --base-href ${{inputs.baseHref}} ${{inputs.customArgs}}
        else
          flutter build web --release --web-renderer=${{inputs.webRenderer}} --base-href ${{inputs.baseHref}} ${{inputs.customArgs}}
        fi
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git config user.name github-actions
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git config user.email github-actions@github.com
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git --work-tree build/web add --all
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git commit -m "Automatic deployment by github-actions"
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git push origin HEAD:${{inputs.targetBranch}} --force
      shell: bash
      working-directory: ${{inputs.workingDir}}
